#!/bin/bash

mkdir build/trilinos
mkdir install/trilinos
cd build/trilinos

rm -Rf CMakeCache.txt CMakeFiles build.ninja

#-DBUILD_SHARED_LIBS:BOOL=OFF
#-DCMAKE_BUILD_TYPE:STRING=release
#-DCMAKE_C_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.5-nvidia-11.2.1-RHEL7/bin/mpicc
#-DCMAKE_CXX_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.5-nvidia-11.2.1-RHEL7/bin/mpic++
#-DCMAKE_Fortran_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.5-nvidia-11.2.1-RHEL7/bin/mpif90
#-DCMAKE_CXX_STANDARD=17
#-DCMAKE_C_FLAGS_RELEASE_OVERRIDE:STRING=-DNDEBUG
#-DCMAKE_CXX_FLAGS_RELEASE_OVERRIDE:STRING=-DNDEBUG
#-DCMAKE_Fortran_FLAGS_RELEASE_OVERRIDE:STRING=-DNDEBUG
#-DCMAKE_C_FLAGS:STRING=-O2
#-w
#-DCMAKE_CXX_FLAGS:STRING=-O2
#-w
#-DCMAKE_Fortran_FLAGS:STRING=-O2
#-w
#-DCMAKE_EXE_LINKER_FLAGS:STRING=
#-DTrilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF
#-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF
#-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF
#-DTrilinos_ENABLE_COMPLEX:BOOL=ON
#-DTrilinos_ENABLE_DEBUG:BOOL=OFF
#-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
#-DTrilinos_ENABLE_FLOAT:BOOL=ON
#-DTrilinos_ENABLE_LINEAR_SOLVER_FACTORY_REGISTRATION:BOOL=ON
#-DTrilinos_SHOW_DEPRECATED_WARNINGS:BOOL=OFF
#-DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING=
#-DTPL_ENABLE_BLAS:BOOL=ON
#-DBLAS_LIBRARY_NAMES=blas
#-DBLAS_LIBRARY_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/netlib-lapack-3.9.0-krv5fbqp4wnicblwvnayzfinbbiyfhs7/lib64
#-DTPL_ENABLE_Boost:BOOL=ON
#-DTPL_Boost_INCLUDE_DIRS:PATH=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/boost-1.77.0-w57ycn7yzj4ppghasurlroqcbyxnw6dy/include
#-DBoost_LIBRARY_DIRS:PATH=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/boost-1.77.0-w57ycn7yzj4ppghasurlroqcbyxnw6dy/lib
#-DTPL_ENABLE_CUDA:BOOL=ON
#-DTPL_ENABLE_LAPACK:BOOL=ON
#-DLAPACK_LIBRARY_NAMES=lapack
#-DLAPACK_LIBRARY_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/netlib-lapack-3.9.0-krv5fbqp4wnicblwvnayzfinbbiyfhs7/lib64
#-DTPL_ENABLE_METIS:BOOL=ON
#-DMETIS_LIBRARY_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/metis-5.1.0-othcovx3cgfc7v3ditphrq2u24sgluub/lib
#-DMETIS_LIBRARY_NAMES=metis
#-DMETIS_INCLUDE_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/metis-5.1.0-othcovx3cgfc7v3ditphrq2u24sgluub/include
#-DTPL_ENABLE_MPI:BOOL=ON
#-DMPI_BASE_DIR:PATH=/projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.5-nvidia-11.2.1-RHEL7
#-DTPL_ENABLE_ParMETIS:BOOL=ON
#-DParMETIS_LIBRARY_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/parmetis-4.0.3-lzzejhgrjafhd5yhckfxrdgrjgut6evn/lib
#-DParMETIS_LIBRARY_NAMES=parmetis;metis
#-DParMETIS_INCLUDE_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/parmetis-4.0.3-lzzejhgrjafhd5yhckfxrdgrjgut6evn/include
#-DTPL_ENABLE_Pthread:BOOL=OFF
#-DSuperLU_LIBRARY_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/superlu-5.2.1-4t6qmkwc5gi6mn267tysosurcmhpwm36/lib
#-DSuperLU_INCLUDE_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/superlu-5.2.1-4t6qmkwc5gi6mn267tysosurcmhpwm36/include
#-DTPL_ENABLE_yaml-cpp:BOOL=OFF
#-DTPL_ENABLE_y12m:BOOL=ON
#-Dy12m_LIBRARY_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/y12m-1.0.0-bzlxj37c2bli653ehebm237djj4jsfyu/lib
#-DTPL_ENABLE_UMFPACK:BOOL=ON
#-DUMFPACK_LIBRARY_DIRS:PATH=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/umfpack-5.1.0-jaedddhuvu7a6k6rey7g5y4qthlyvo6d/lib
#-DUMFPACK_INCLUDE_DIRS:PATH=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/umfpack-5.1.0-jaedddhuvu7a6k6rey7g5y4qthlyvo6d/include
#-DUMFPACK_LIBRARY_NAMES=umfpack;amd
#-DTPL_ENABLE_Scotch:BOOL=ON
#-DScotch_LIBRARY_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/scotch-6.0.4-wy6swmrlwet4ssz37rnd5sygpoiac364/lib
#-DScotch_INCLUDE_DIRS=/scratch/malphil/code/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-rhel7-x86_64/gcc-8.3.0/scotch-6.0.4-wy6swmrlwet4ssz37rnd5sygpoiac364/include
#-DTPL_ENABLE_CUSPARSE:BOOL=ON
#-DKokkos_ENABLE_CUDA_UVM:BOOL=ON
#-DKokkos_ENABLE_CUDA_LAMBDA:BOOL=ON
#-DKokkos_ENABLE_CUDA_CONSTEXPR:BOOL=ON
#-DTpetra_ASSUME_CUDA_AWARE_MPI:BOOL=OFF
#-DKokkosKernels_INST_MEMSPACE_CUDAUVMSPACE=ON
#-DTpetra_ALLOCATE_IN_SHARED_SPACE=ON
#-DKokkos_ARCH_VOLTA70:BOOL=ON
#-DTrilinos_ENABLE_Amesos:BOOL=ON
#-DTrilinos_ENABLE_Amesos2:BOOL=ON
#-DTrilinos_ENABLE_Anasazi:BOOL=ON
#-DTrilinos_ENABLE_AztecOO:BOOL=ON
#-DTrilinos_ENABLE_Belos:BOOL=ON
#-DTrilinos_ENABLE_Epetra:BOOL=ON
#-DTrilinos_ENABLE_EpetraExt:BOOL=ON
#-DTrilinos_ENABLE_Galeri:BOOL=OFF
#-DTrilinos_ENABLE_Gtest:BOOL=OFF
#-DTrilinos_ENABLE_Ifpack:BOOL=ON
#-DTrilinos_ENABLE_Ifpack2:BOOL=ON
#-DTrilinos_ENABLE_Intrepid:BOOL=ON
#-DTrilinos_ENABLE_Intrepid2:BOOL=ON
#-DTrilinos_ENABLE_Isorropia:BOOL=OFF
#-DTrilinos_ENABLE_Kokkos:BOOL=ON
#-DTrilinos_ENABLE_KokkosCore:BOOL=ON
#-DTrilinos_ENABLE_KokkosContainers:BOOL=ON
#-DTrilinos_ENABLE_MiniTensor:BOOL=ON
#-DTrilinos_ENABLE_ML:BOOL=ON
#-DTrilinos_ENABLE_MOOCHO:BOOL=OFF
#-DTrilinos_ENABLE_MueLu:BOOL=ON
#-DTrilinos_ENABLE_OpenMP:BOOL=OFF
#-DTrilinos_ENABLE_Pamgen:BOOL=ON
#-DTrilinos_ENABLE_ROL:BOOL=ON
#-DTrilinos_ENABLE_RTOp:BOOL=ON
#-DTrilinos_ENABLE_Rythmos:BOOL=OFF
#-DTrilinos_ENABLE_Sacado:BOOL=ON
#-DTrilinos_ENABLE_SEACAS:BOOL=OFF
#-DTrilinos_ENABLE_Shards:BOOL=ON
#-DTrilinos_ENABLE_ShyLU_NodeTacho:BOOL=ON
#-DTrilinos_ENABLE_ShyLU_NodeHTS:BOOL=ON
#-DTrilinos_ENABLE_STK:BOOL=OFF
#-DTrilinos_ENABLE_Stokhos:BOOL=OFF
#-DTrilinos_ENABLE_SuperLU5_API:BOOL=ON
#-DTrilinos_ENABLE_Teuchos:BOOL=ON
#-DTrilinos_ENABLE_Teko:BOOL=ON
#-DTrilinos_ENABLE_ThreadPool:BOOL=ON
#-DTrilinos_ENABLE_Thyra:BOOL=ON
#-DTrilinos_ENABLE_ThyraEpetraExtAdapters:BOOL=ON
#-DTrilinos_ENABLE_Tpetra:BOOL=ON
#-DTrilinos_ENABLE_TrilinosCouplings:BOOL=OFF
#-DTrilinos_ENABLE_Triutils:BOOL=ON
#-DTrilinos_ENABLE_Xpetra:BOOL=ON
#-DTrilinos_ENABLE_Zoltan:BOOL=ON
#-DTrilinos_ENABLE_Zoltan2:BOOL=ON
#-DTrilinos_ENABLE_ShyLU_NodeFastILU:BOOL=ON
#-DTrilinos_ENABLE_PanzerExprEval:BOOL=ON
#-DAmesos_ENABLE_SuperLU:BOOL=ON
#-DAmesos2_ENABLE_ShyLU_NodeTacho:BOOL=ON
#-DAmesos2_ENABLE_SuperLU:BOOL=ON
#-DAztecOO_ENABLE_AZLU:BOOL=ON
#-DBelos_ENABLE_Xpetra:BOOL=OFF
#-DIfpack2_ENABLE_ThyraTpetraAdapters=ON
#-DKokkos_ENABLE_CUDA:BOOL=ON
#-DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON
#-DKokkos_ENABLE_DEPRECATED_CODE:BOOL=OFF
#-DKokkos_ENABLE_OPENMP:BOOL=OFF
#-DKokkosKernels_ENABLE_SUPERNODAL_SPTRSV=OFF
#-DML_ENABLE_METIS:BOOL=OFF
#-DML_ENABLE_ParMETIS:BOOL=OFF
#-DML_ENABLE_SuperLU:BOOL=OFF
#-DPamgen_ENABLE_Boost:BOOL=OFF
#-DPamgen_ENABLE_Extras:BOOL=OFF
#-DROL_ENABLE_EXAMPLES:BOOL=OFF
#-DROL_ENABLE_TESTS:BOOL=OFF
#-DSacado_ENABLE_KokkosCore:BOOL=ON
#-DTacho_ENABLE_INT_INT:BOOL=ON
#-DTpetra_INST_INT_LONG:BOOL=ON
#-DTpetra_INST_INT_LONG_LONG:BOOL=OFF
#-DTpetra_INST_OPENMP:BOOL=OFF
#-DTpetra_INST_SERIAL:BOOL=ON
#-DZoltan_ENABLE_METIS:BOOL=OFF
#-DZoltan_ENABLE_Scotch:BOOL=OFF
#-DZoltan2_ENABLE_Experimental:BOOL=ON
#-DIfpack2_ENABLE_ShyLU_NodeFastILU:BOOL=ON
#-DAmesos2_ENABLE_UMFPACK:BOOL=ON
#-DZoltan2_ENABLE_Scotch:BOOL=ON

ARGS=(
  -GNinja
  # -D Trilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake
  # -D CMAKE_BUILD_TYPE=RELWITHDEBINFO
  -D CMAKE_BUILD_TYPE=DEBUG
  -D Trilinos_ENABLE_DEBUG=ON
  -D Trilinos_ENABLE_TESTS=OFF
  -D Trilinos_ENABLE_ShyLU_NodeFastILU=OFF
  -D CMAKE_EXPORT_COMPILE_COMMANDS=1 
  -D Ifpack2_ENABLE_EXPLICIT_INSTANTIATION=1
  -D Trilinos_ENABLE_Ifpack2=ON
  -D Trilinos_ENABLE_MueLu=ON
  -D MueLu_ENABLE_EXAMPLES=ON
  -D Ifpack2_ENABLE_TESTS=ON
  -D Trilinos_ENABLE_Teko=ON
  -D Trilinos_ENABLE_Intrepid2=OFF
  -D Trilinos_ENABLE_COMPLEX=ON
  -D Trilinos_ENABLE_FLOAT=ON
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
  -D TPL_ENABLE_CUDA:BOOL=ON
  -D Kokkos_ENABLE_CUDA_UVM:BOOL=ON
  -D Kokkos_ENABLE_CUDA_LAMBDA:BOOL=ON
  -D Kokkos_ENABLE_CUDA_CONSTEXPR:BOOL=ON
  -D Tpetra_ASSUME_CUDA_AWARE_MPI:BOOL=OFF
  -D KokkosKernels_INST_MEMSPACE_CUDAUVMSPACE=ON
  -D Tpetra_ALLOCATE_IN_SHARED_SPACE=ON
  -D Kokkos_ARCH_VOLTA70:BOOL=ON
  -D Kokkos_ENABLE_CUDA:BOOL=ON
  -D Kokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON
  -D TPL_ENABLE_CUSPARSE:BOOL=ON
  -D BUILD_SHARED_LIBS:BOOL=OFF
  -D CMAKE_BUILD_TYPE:STRING=release
  -D CMAKE_C_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.5-nvidia-11.2.1-RHEL7/bin/mpicc
  -D CMAKE_CXX_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.5-nvidia-11.2.1-RHEL7/bin/mpic++
  -D CMAKE_Fortran_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/4.0.5-nvidia-11.2.1-RHEL7/bin/mpif90
  -D CMAKE_CXX_STANDARD=17
  -D CMAKE_INSTALL_PREFIX=../../install/trilinos
)

set -o pipefail
cmake "${ARGS[@]}" $TRILINOS | tee config.log
